### ISSUE TITLE
Add some vertex color quick buttons

### ISSUE THREAD

**Issue by Simarilius-uk** [WolvenKit/Cyberpunk-Blender-add-on#113]
![image](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/assets/29640139/986b3775-150d-46cb-94f0-79af1f277b2e)

Apply color tones for vertices from plugin menu instead of adding a mesh from the game with the desired vertex color attribute to the project

requested by 𝑴𝑨𝑿_𝑺𝑨5 on discord.

**Comment by DoctorPresto** [comment]
I think this is a great idea. Were any particular colours requested/documented in the request?

A couple I know: 

Primary Taillight Hex: A90101
Secondary Taillight  Hex: E7010
Primary  Headlight Hex: 7C0101
Secondary Amber/Marker Light  Hex: CB0101

**Comment by Simarilius-uk** [comment]
How about rather than the 0123 buttons we have a drop down that we populate from a text file in resources, then people can add their own to that list if they need something?

**Comment by DoctorPresto** [comment]
A drop down and sneaks just parts definitely bakes sense,, but seems like we should at least include at least a small number of preset colours as well.. I don't think it would be of much value to only include a way to save the colours.

**Comment by Simarilius-uk** [comment]
I meant we have a text file with some presets somewhere thats easy to get to and edit. wouldnt even bother adding the way to save more to the ui, people can just edit the file in resources.

**Comment by DoctorPresto** [comment]
> people can just edit the file in resources.

I'm not sure this would be a very user friendly approach. Seems like ideal state would be to just click a single button, have a small modal open up to ask for a name and then whatever colour the vert paint tool is on is saved, rather than needing to copy hex/rgb/hsv/whatever bpy lets us use for vert colour, navigate to the plugin directory, open some file, handwrite an identifier and paste the colour in. The former also leaves open the ability to still go in to the file and manually edit it if desired, just doesn't demand it of you.

**Comment by Simarilius-uk** [comment]
I mean if you can be bothered doing all that, great, but how about for first you just slap the buttons in and load from a file? :D

**Comment by DoctorPresto** [comment]
I think it should be the same amount of work :D

**Comment by DoctorPresto** [comment]
added in my fork, will be in next major release
