### ISSUE TITLE
Some materials missing when importing valentino cyberware

### ISSUE THREAD

**Issue by philipl** [WolvenKit/Cyberpunk-Blender-add-on#124]
When I import `base\characters\garment\gang_valentino\legs\l0_007_tights__a0_005_cyber\l0_007_wa_tights__a0_005_cyber.mesh`, all the `foo_plastic` appearances are left out. I don't see any errors or warnings associated with the materials. The remaining materials all look correct.

When I was previously running where the add-on couldn't find the files due to path problems, it would import all the material names into blender, so the `foo_plastic` ones would be in the list, but obviously, all the material configurations would be empty.

**Comment by DoctorPresto** [comment]
Which version of the plugin/blender/Wolvenkit/the game?

**Comment by philipl** [comment]
* Game: 2.12
* Wolvenkit: 8.13.0
* Add-On: 7c666418f9fb6a981f3addd2a92fa9fc931d50aa

**Comment by DoctorPresto** [comment]
Thanks! Just to confirm, are the game/Wolvenkit/blender all running in Linux/windows vm?

**Comment by philipl** [comment]
Wolvenkit is running in a windows VM. Everything else is on the Linux side. I used shared storage to let wolvenkit generate the depot and have it accessible on the host.

**Comment by DoctorPresto** [comment]
I assigned Sim here because I don't have a non Windows system to test with but I know you've had some commits lately too. If you have the time and feel like taking a look at this at all, please feel free to assign yourself. We all really appreciate the contributions and the input! Imo,  we're long overdue for some proper verbose logging we can switch on for debugging this sort of stuff too

**Comment by Simarilius-uk** [comment]
Theres a bunch of path manipulations that break if you move platform os.basepath doesnt work if the path is from another systems setting, so things like creating the layer names in the multilayer breaks. I've fixed most of it in getting the depot remappable, but am still testing. 
code is in this branch, https://github.com/Simarilius-uk/Cyberpunk-Blender-add-on/tree/remapDepot
but I wasnt expecting to get it working this easily and so hadnt gone back to a clean checkout before i started, so that branch has other wip stuff in it too. (remappable depot, and sector export as a menu item)

**Comment by Simarilius-uk** [comment]
also just realised mlmask imports been broken for about a month and we hadnt noticed. oops

**Comment by DoctorPresto** [comment]
fixed in [PR126](https://github.com/WolvenKit/Cyberpunk-Blender-add-on/pull/126)
