### ISSUE TITLE
'NoneType' object has no attribute 'update' on GLB export

### ISSUE THREAD

**Issue by Zhincore** [WolvenKit/Cyberpunk-Blender-add-on#146]
Hey, 
I get the following error when trying to export a mesh:
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\__init__.py", line 1256, in execute
    export_cyberpunk_glb(context, self.filepath, self.export_poses, self.export_visible, self.limit_selected, self.static_prop)
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\i_scene_cp77_gltf\exporters\glb_export.py", line 161, in export_cyberpunk_glb
    options.update(cp77_mesh_options())
AttributeError: 'NoneType' object has no attribute 'update'
```

**Comment by DoctorPresto** [comment]
Do you happen to be using blender 3.6 installed through steam?

**Comment by Zhincore** [comment]
Yes, exactly, should I update to 4.1 or stop using steam?

**Comment by DoctorPresto** [comment]
Either one of those would solve the issue for you, my suggestion would be to just update to 4.1 through steam since you're already using steam to manage Blender and were technically not supporting versions below 4.x anymore, but if you need to use 3.6 for some reason, installing it from blender.com will also solve the problem.

I haven't had a chance to look into why this actually happens, but as far as I've found so far, it's limited to old versions of blender installed through Steam

**Comment by DoctorPresto** [comment]
I've closed your issue, but if this persists for you after you try either of the solutions above, please open another and I'll dig into this further
